### ISSUE TITLE
Compiled for java 15

### ISSUE THREAD

**Issue by jDzames** [YunaBraska/nats-streaming-server-embedded#34]
Not necessary an issue, more of suggestion/idea to make library available to wider set of users, as many projects are still far from using java 15. 

For example we use java 8 still and after including this lib to project build fails as lib classes were compiled for java 15 (`target` option in compilation plugin). See https://maven.apache.org/plugins/maven-compiler-plugin/examples/set-compiler-source-and-target.html

Or this - https://www.baeldung.com/maven-java-version#java9 (maybe this would be enough :thinking: )

**Comment by YunaBraska** [comment]
Totally valid, I will switch back to LTS versions like 11 and probably make one tag for Java 8 as well

**Comment by YunaBraska** [comment]
@jDzames I wasn't using too much new java features. So this library is compiled as java 8 now.
Let me know if it worked :)

**Comment by jDzames** [comment]
Thanks! It works now. :+1:  (I just needed to raise all spring versions due to classpath errors.)
You can close this now.
