### ISSUE TITLE
Spring + tests complications

### ISSUE THREAD

**Issue by jDzames** [YunaBraska/nats-streaming-server-embedded#35]
Hello. 
First, thanks once more for porting this lib to java 8.

I've been testing this in our project, we would like to use it for integration tests... But I noticed that after merely adding lib to project (not yet using it anywhere), Spring context keeps getting recreated (not sure if it's per test or what exact frequency, but it was not happening before). Can it be somehow related to EnableNatsServerContextCustomizer(Factory)? Or it's something caused in combination with our setup.. :thinking: 

And actually ... 
1. I needed to bump Spring dependencies versions by significant amount to make it work (I doubt this gets to all of our platform really)
2. We would prefer to manage nats lifecycle ourselves (start and stop server ourselves) 

This leads me to ask whether you have considered providing embedded nats lib without Spring?
I could imagine one lib with embedded nats core (with nats logic and start, stop and config methods) and another lib that would be Spring wrapper for that, with annotation and bean logic...? What's your opinion on this?

**Comment by YunaBraska** [comment]
Oh I have to thank you for your help and patience to make this library better.
For the spring context recreation, I will have a look.
And yes, I was considering already to split my libraries in multiple parts. Like you said pure java, spring and then the new quarkus. just didn't had time for quarkus yet. I think that will be my first step to split this project now. shouldn't be that hard. If the required dependencies doesn't do any issues to you, then you can also use this library without the annotation as well https://github.com/YunaBraska/nats-streaming-server-embedded/blob/master/src/test/java/berlin/yuna/natsserver/logic/NatsServerWithoutAnnotationTest.java

**Comment by jDzames** [comment]
Using lib without annotation - yes, I tried it... Well, it worked fine, just those same issues - context being recreated all the time during tests.. And still - as you said - pure java lib, without Spring - that would be ideal for us. :slightly_smiling_face: 

And good luck then, I'll be around to check it if/when you split it (as you said you plan to do it as next thing... :+1: ). Should be easy for us then to fit it into our use-case.

**Comment by YunaBraska** [comment]
@jDzames its extracted now to a pure java library: https://github.com/YunaBraska/nats-streaming-server
https://github.com/YunaBraska/nats-streaming-server-embedded is now just the wrapper

**Comment by YunaBraska** [comment]
Regarding the recreating Spring Context issue, I would need more information of the setup or an example project so I can reproduce it.

**Comment by jDzames** [comment]
Thanks for quick help!

Spring Context issue - hmm, if it's not present in standard project with multiple integration tests in multiple classes, then it would be something specific for our setup... I am really not sure what would cause it then. If you want I can describe our setup, but with pure java library we would now happily use that. I am going to use pure nats java lib today, will let you know how it works, but I doubt there can be any problem. :+1:

**Comment by jDzames** [comment]
Yep, works like a charm! Thanks!
